PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

DELETE { ?s ?p ?o . }

WHERE {
  ?s ?p ?o .
  
  ### Optional predicate filtering ###
  #BIND(dcterms:title AS ?predicate)
  
  ### Optional fitlering by class of subject ###
  #?s a foaf:Person .
  
  # Enter value that should be removed, default is an empty string
  BIND('' AS ?toRemove)
  
  
  ### Don't modify below this line ### 
  FILTER(isLiteral(?o))
  
  FILTER(
    IF(
      BOUND(?predicate),
      ?p = ?predicate,
      true
    )
  )
  
  FILTER(STR(?o) = ?toRemove)
}