PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

DELETE { ?s ?p ?o . }

WHERE {
  ### Predicate filtering ###
  # Any predicate
  ?s ?p ?o .
  # or single predicate
  #?s dcterms:title ?o .
  
  ### Optional fitlering by class of subject ###
  #?s a foaf:Person .
  
  # Enter regular expression to use for filtering, default is empty string
  BIND('^$' AS ?regexp)
  
  
  ### Don't modify below this line ### 
  FILTER(isLiteral(?o))
  FILTER(REGEX(?o, ?regexp))
}